security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UtilisateursAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
            # Other firewall configurations...

    access_control:
        - { path: ^/article/new, roles: ROLE_EDITOR }
        - { path: ^/article/\d+/edit, roles: ROLE_EDITOR }
        - { path: ^/article, roles: ROLE_USER }
        - { path: ^/article, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # pour lec commentaires 
        - { path: ^/article, roles: ROLE_USER }
        - { path: ^/article, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Assuming everyone can view articles

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_EDITOR, ROLE_USER]
        ROLE_EDITOR:      ROLE_USER
        ROLE_USER:        ~

    # Other global security configurations...

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
